feat(appbar): added appbar
consenz-io/webapp pull request #112
Opened 2022-08-15 18:53 UTC by yishain11

2022-08-15 18:54 UTC, yishain11 commented
PR for appbar.
 log for sowhing state fn is just because the ts error when not using it.
the usage is a part of advance use, need to talk it over during review.

2022-08-31 07:54 UTC, avirankatz requested changes
Please see requested changes

2022-08-31 07:54 UTC, avirankatz commented on frontend/src/components/Appbar/types.ts
> +}
Let's move this into `Appbar.tsx` and remove Appbar dir (same thing we did with other components)

2022-08-31 07:54 UTC, avirankatz commented on frontend/src/components/Sidebar/Sidebar.tsx
> +        <Link to="/" title={t(StringBank.GOTO_HOMEPAGE_TITLE)} style={{ display: 'flex' }}>
Is this intended?

2022-08-31 07:54 UTC, avirankatz commented on frontend/src/pages/NewAgreement.tsx
> +        agreementName={agreementName || 'My New Agreement'}
```suggestion
        agreementName={agreementName}
```

2022-08-31 07:54 UTC, avirankatz commented on frontend/src/pages/NewAgreement.tsx
> +          console.log('closing appbar');
Let's replace this with navigation back. We may use `useNavigation` from react router

2022-08-31 07:54 UTC, avirankatz commented on frontend/src/components/Appbar/Appbar.tsx
> +  console.log('setCompleted', setCompleted);
Could you please remove this print?

2022-09-01 05:54 UTC, avirankatz approved these changes

2022-09-01 05:55 UTC, merged