103 del btn menu
consenz-io/webapp pull request #128
Opened 2022-08-29 08:41 UTC by yishain11

2022-08-30 07:15 UTC, avirankatz requested changes
Great PR. Please see the requested change

2022-08-30 07:15 UTC, avirankatz commented on frontend/src/components/AgreementCard.tsx
> +        },
This could be a one-liner

2022-08-30 07:15 UTC, avirankatz commented on frontend/src/components/AgreementCard.tsx
> +                  menuItems={getMenuItems()}
Great refactor

2022-08-30 14:27 UTC, yishain11 commented on frontend/src/components/AgreementCard.tsx
> +                  menuItems={getMenuItems()}
thx

2022-08-31 07:54 UTC, avirankatz approved these changes

2022-08-31 07:54 UTC, merged