119 prem section card
consenz-io/webapp pull request #136
Opened 2022-09-04 12:48 UTC by yishain11

2022-09-11 12:08 UTC, avirankatz commented
@yishain11 Following our conversation, waiting for your cue before reviewing this

2022-09-13 14:03 UTC, avirankatz requested changes
General notes:
- [ ] When using `<Typography>` - use variants instead of sx as much as possible
- [ ] Avoid hard-coded strings, use `t(...)`
- [ ] gaps, spacing, margin, padding should use multiples of 4px
- [ ] arrows should be reversed in RTL mode
- [ ] No need for SectionCard directory

2022-09-13 14:03 UTC, avirankatz commented on frontend/src/pages/AgreementPage.tsx
> +              <Stack direction="column" rowGap="2rem" width="70%">
No need for width here. Section cards should take available space.
Instead - The Stack containing all of the chapters should use `maxWidth="md"`

2022-09-13 15:49 UTC, avirankatz commented
SectionCard.tsx should be directly under components directory

2022-09-14 13:01 UTC, avirankatz requested changes
Much better. See minor requested changes

2022-09-14 13:20 UTC, yishain11 commented on frontend/src/pages/AgreementPage.tsx
>              <Typography
done

2022-09-14 13:21 UTC, yishain11 commented on frontend/src/pages/AgreementPage.tsx
>                direction="row"
used spacing

2022-09-14 13:35 UTC, yishain11 commented on frontend/src/components/SectionCard.tsx
> +  const CheckedIconRender = (props: { isSelected: boolean }) => {
done

2022-09-14 13:35 UTC, yishain11 commented on frontend/src/components/SectionCard.tsx
> +            <CheckedIconRender isSelected={true} />
done

2022-09-14 13:51 UTC, avirankatz approved these changes

2022-09-14 13:51 UTC, merged