feat(snackbar): added snackbar to copy url
consenz-io/webapp pull request #157
Opened 2022-09-20 09:23 UTC by yishain11

2022-09-23 12:18 UTC, avirankatz requested changes
I love the bite-sized PR! Please see the the requested changes

2022-09-23 12:18 UTC, avirankatz commented on frontend/src/components/NewAgreement/AgreementCreatedSuccessfully.tsx
> +  const [snackbarOpen, setSnackbarOpen] = useState(false);
Suggestion: let's rename `snackbarOpen` to `isSnackbarOpen`

2022-09-23 12:18 UTC, avirankatz commented on frontend/src/components/NewAgreement/AgreementCreatedSuccessfully.tsx
> +            message="URL Copied Successfully"
Please use string bank

2022-09-28 07:55 UTC, yishain11 commented on frontend/src/components/NewAgreement/AgreementCreatedSuccessfully.tsx
> +            message="URL Copied Successfully"
done

2022-09-28 14:09 UTC, avirankatz approved these changes

2022-09-28 14:09 UTC, merged