151 foldable chapters
consenz-io/webapp pull request #174
Opened 2022-09-29 13:40 UTC by yishain11

2022-09-30 06:00 UTC, avirankatz requested changes
Looks and behaves good! Two minor requests:

- [ ] Every chapter should be expanded by default (`defaultExpanded` prop allows that)
- [ ] Let's use chapter.id as key instead of a random string

2022-09-30 06:01 UTC, avirankatz commented on frontend/src/pages/AgreementPage.tsx
> +              key={generateRandString()}
Let's use `defaultExpanded` prop here

2022-10-02 12:48 UTC, yishain11 commented on frontend/src/pages/AgreementPage.tsx
> +              key={generateRandString()}
done

2022-10-02 12:53 UTC, yishain11 commented on frontend/src/pages/AgreementPage.tsx
> +              key={generateRandString()}
done

2022-10-02 17:14 UTC, avirankatz approved these changes

2022-10-02 17:14 UTC, merged