228 comments section
consenz-io/webapp pull request #240
Opened 2022-11-15 14:12 UTC by yishain11

2022-11-15 14:56 UTC, avirankatz requested changes
- [ ] Move comments query to section context
- [x] Remove all console logs
- [ ] We should use a single comments container (before the array rendering)
- [ ] Shorten calcTimeAgoFromDate

2022-11-16 10:06 UTC, yishain11 commented on frontend/src/utils/functions.ts
> +}
cool implementation!

2022-11-17 14:36 UTC, yishain11 commented on frontend/src/pages/Section.tsx
> +      addComment!(commentVars);
this fix results in ts error: 
Object is possibly 'undefined'.ts(2532)
Parsing error: Identifier expected.eslint

same with only ?

2022-11-17 14:49 UTC, yishain11 commented on frontend/src/pages/Section.tsx
> +  }, [displayedVersion]);
causes infinite loop

2022-11-17 14:50 UTC, yishain11 commented on frontend/src/pages/Section.tsx
> +                comments.core_comments.map((comment: Comment) => {
done

2022-11-17 14:51 UTC, yishain11 commented on frontend/src/pages/Section.tsx
> +                      sx={{ marginBottom: '2rem' }}
done

2022-11-22 08:12 UTC, avirankatz approved these changes

2022-11-22 08:12 UTC, merged