235 new comment textarea
consenz-io/webapp pull request #241
Opened 2022-11-15 17:51 UTC by yishain11

2022-11-16 13:16 UTC, avirankatz reviewed
- [x] Revert core_comments.yaml

2022-11-16 13:50 UTC, avirankatz requested changes
- [x] Revert core_comments.yaml
- [ ] Revert core_section_versions.yaml
- [ ] Rename AddComment (constant in mutations) to addComment
- [ ] Rename addCommentVars (interface in section context) to AddCommentVars
- [ ] authorId inside add comment vars should be automatically inserted in the db (trigger), we shouldn't send it as a variable
- [ ] Replace ContentEditor with a simple TextArea, we don't allow styling in comments
- [ ] Submit comment button > onclick: extract handler to component scope
- [ ] Section.tsx:264 > use 'Publish' from string bank

2022-11-17 10:00 UTC, avirankatz requested changes
- [ ] TextAreaAutosize - extract on change handler to component scope
- [ ] remove author from add comment vars
- [ ] style: avoid hard coded widths and heights (Section.tsx box and text area)
- [ ] style: use color const instead of hard coded string (Section.tsx:253)
- [ ] text area: verify that all styling is necessary; remove unnecessary styling
- [ ] text area: remove ref and usages
- [ ] Section.tsx:271 - remove hard coded color string; use const from theme instead

2022-11-17 11:46 UTC, avirankatz reviewed
See suggestion for text area

2022-11-17 11:46 UTC, avirankatz commented on frontend/src/pages/Section.tsx
> +                </Button>
```suggestion
                <TextField
                  placeholder={t(StringBank.ADD_COMMENT_IN_SECTION)}
                  onChange={(data) => {
                    const commentText = data.target.value;
                    if (commentText !== '') {
                      setNewComment(commentText);
                      return;
                    }
                    data.target.value = '';
                    setNewComment('');
                  }}
                  minRows={3}
                  multiline
                  fullWidth
                />
              </Stack>
              <Stack direction="row" justifyContent="end">
                <Button
                  disabled={!newComment}
                  sx={{ paddingX: 0, marginY: 1 }}
                  onClick={handelAddComment}
                >
                  {t(StringBank.PUBLISH)}
                </Button>
```

2022-11-17 14:56 UTC, yishain11 commented
> * [x]  TextAreaAutosize - extract on change handler to component scope
> * [x]  remove author from add comment vars
> * [ ]  style: avoid hard coded widths and heights (Section.tsx box and text area)
> * [ ]  style: use color const instead of hard coded string (Section.tsx:253)
> * [ ]  text area: verify that all styling is necessary; remove unnecessary styling
> * [ ]  text area: remove ref and usages
> * [x]  Section.tsx:271 - remove hard coded color string; use const from theme instead

text area: remove ref and usages: 
this is needed in order to make the comment box empty after publishing.

2022-11-22 08:34 UTC, merged