245 arrows nav versions
consenz-io/webapp pull request #250
Opened 2022-11-22 16:48 UTC by yishain11

2022-11-27 18:16 UTC, nadavmoreno requested changes

2022-11-27 18:16 UTC, nadavmoreno commented on frontend/src/components/AddCommnetBox.tsx
> +import { FC, useContext, useState } from 'react';
@yishain11 fix typo in file name

2022-11-27 18:16 UTC, nadavmoreno commented on frontend/src/components/AddCommnetBox.tsx
> +  function handleAddComment() {
@yishain11 space up line

2022-11-27 18:16 UTC, nadavmoreno commented on frontend/src/components/DispalySection.tsx
> +  function handleShare() {
@yishain11 space up line

2022-11-28 09:21 UTC, yishain11 commented on frontend/src/components/AddCommnetBox.tsx
> +import { FC, useContext, useState } from 'react';
done

2022-11-28 09:21 UTC, yishain11 commented on frontend/src/components/AddCommnetBox.tsx
> +  function handleAddComment() {
done

2022-11-28 09:21 UTC, yishain11 commented on frontend/src/components/DispalySection.tsx
> +  function handleShare() {
done

2022-11-29 11:27 UTC, merged