227 moderator del section version
consenz-io/webapp pull request #254
Opened 2022-11-23 12:54 UTC by yishain11

2022-11-24 13:18 UTC, avirankatz requested changes

2022-11-24 13:18 UTC, avirankatz commented on frontend/src/pages/Section.tsx
> +                          comments && comments.length > 0
```suggestion
                          comments?.length
```

2022-11-24 13:18 UTC, avirankatz commented on frontend/src/pages/Section.tsx
> +                      disabled={comments ? comments.length > 0 : false}
```suggestion
                      disabled={!!comments?.length}
```

2022-11-27 11:00 UTC, yishain11 commented on frontend/src/pages/Section.tsx
> +                      disabled={comments ? comments.length > 0 : false}
done

2022-12-04 09:34 UTC, merged