257 rtl fixes
consenz-io/webapp pull request #258
Opened 2022-11-24 12:11 UTC by yishain11

2022-11-24 13:30 UTC, avirankatz requested changes

2022-11-24 13:30 UTC, avirankatz commented on frontend/src/components/Appbar.tsx
> +                  <StepLabel StepIconProps={{ sx: { paddingX: '1rem' } }}>{step}</StepLabel>
```suggestion
                  <StepLabel StepIconProps={{ sx: { paddingX: 1 } }}>{step}</StepLabel>
```

2022-11-27 10:51 UTC, yishain11 commented on frontend/src/components/Appbar.tsx
> +                  <StepLabel StepIconProps={{ sx: { paddingX: '1rem' } }}>{step}</StepLabel>
done

2022-11-27 16:56 UTC, merged

2022-11-27 17:17 UTC, nadavmoreno commented on frontend/src/pages/Agreement.tsx
>              <Typography variant="h1" marginRight={2}>
@yishain11 remove `marginRight`

2022-11-27 17:17 UTC, nadavmoreno commented on frontend/src/pages/Agreement.tsx
> +          <Stack direction="row" alignItems="end" gap={0.5}>
@yishain11 change `gap` to `1.5`