added context for jwt structure, based on issue #21 requirements
consenz-io/webapp pull request #31
Opened 2022-06-08 11:06 UTC by yishain11

2022-06-08 11:55 UTC, avirankatz commented
Closes #21

2022-06-08 12:36 UTC, avirankatz commented on frontend/src/services/services.tsx
> +const AuthContext = createContext<any | null>(null);
Could you create an interface for strongly typed AuthContext, to be used instead of `<any>`? something like `IAuthContext`?

2022-06-08 12:41 UTC, avirankatz requested changes

2022-06-08 12:41 UTC, avirankatz commented on frontend/src/pages/Home/Home.tsx
> +  const { getJwt, storeJwt } = useContext(AuthContext);
`getJwt` has no usages

2022-06-13 11:55 UTC, yishain11 commented on frontend/src/pages/Home/Home.tsx
> +import Brightness4Icon from "@mui/icons-material/Brightness4";
added @mui/icons-material to package.json

2022-06-13 12:14 UTC, yishain11 commented
gone through all the messages, fixed them all.

2022-06-14 09:12 UTC, merged